########################==》》专业筛选《《==###############################
#仅支持专业分组筛选
groups:
  - group:
      major: 工商管理
#  - group:
#      major: 市场营销

#################### ====》》专业可用字段《《=== ############################
###财务管理   电子商务  工商管理  工业工程   会计学   经济统计学  市场营销  信息管理与信息系统###
##########################################################################
SchoolHost: fzu.campusphere.net
Cookie: MOD_AUTH_CAS=wwGXeKtk6MuAY2c541870
signkeyword: "核酸"
keyword1: "福州大学"
keyword2: "摸排"
Judgmentdate: false

########################==》》变量说明《《==########################
##一、studentjsonfile: 'cs.txt'—— 学号以及qq对应数据，可自行添加。不包含延毕同学  ##
##二、keyword: ""——————— 筛选信息收集的关键字                                            ##
##三、USEQQmessage: false—— true/false 使用qq机器人私聊，请确保手动提前打开   ##
##四、QQMessage: —————— qq私聊信息内容。                                                  ##
##五、result：—————————值不为空时打印汇总信息                                         ##
##################################################################
studentjsonfile: 'cs.txt'

